export const categories = [
  "Accommodation/Tenancy",
  "Assist Access/Maintain Employ",
  "Assist Personal Activities",
  "Assist Prod-Pers Care/Safety",
  "Assist-Life Stage/ Transition",
  "Assist-Travel/Transport",
  "Assistive Equip-Recreation",
  "Assistive Prod-Household Task",
  "Behaviour Support",
  "Comms & Info Equipment",
  "Community Nursing Care",
  "Custom Prosthetics",
  "Daily Tasks/Shared Living",
  "Development-Life Skills",
  "Early Childhood Supports",
  "Ex Phys Pers Training",
  "Group/Centre Activities",
  "Hearing Equipment",
  "Home Modification",
  "Household Tasks",
  "Innov Community Participation",
  "Interpret/Translate",
  "Participate Community",
  "Personal Activities High",
  "Personal Mobility Equipment",
  "Plan Management",
  "Spec Support Employ",
  "Specialised Disability Accommodation",
  "Specialised Driver Training",
  "Support Coordination",
  "Therapeutic Supports",
  "Vehicle Modifications",
  "Vision Equipment",
];

export const SeoKeyboards = [
  "local service platform",
  "local service listing",
  "nearby services",
  "find service provider",
  "online service platform",
  "book local services",
  "local business platform",
  "local marketplace",
  "hire local providers",
  "service booking app",
  "local services near me",
  "best local services",
  "list your service online",
  "find local business",
  "local service hub",
  "local services directory",
  "local service marketplace",
  "find trusted service provider",
  "online booking platform",
  "best service app",
  "become a service provider",
  "register my business online",
  "list my service for free",
  "create a business page",
  "join service platform",
  "promote my business locally",
  "business listing website",
  "advertise my business online",
  "get customers online",
  "how to join nearheal",
  "register as a provider",
  "business promotion site",
  "grow your business locally",
  "get more clients online",
  "best business listing site",
  "create service profile",
  "sign up as provider",
  "small business promotion site",
  "how to add my shop online",
  "free listing site for services",
  "hospital near me",
  "clinic near me",
  "doctor appointment near me",
  "book doctor online",
  "pharmacy near me",
  "dentist near me",
  "best dentist in Australia",
  "skin specialist near me",
  "eye hospital near me",
  "dermatologist near me",
  "ENT specialist near me",
  "pediatrician near me",
  "home nursing services",
  "online consultation doctor",
  "cardiologist near me",
  "orthopedic doctor near me",
  "gynecologist in Australia",
  "best physiotherapist near me",
  "blood test lab near me",
  "X-ray center near me",
  "diagnostic center near me",
  "emergency ambulance service",
  "home health care services",
  "salon near me",
  "beauty parlour near me",
  "spa booking near me",
  "barber shop near me",
  "haircut near me",
  "bridal makeup artist",
  "nail salon near me",
  "massage spa in Australia",
  "men’s salon near me",
  "beauty treatment salon",
  "threading and waxing near me",
  "hair spa in Australia",
  "facial services nearby",
  "best makeup artist",
  "home salon services",
  "affordable salon in Australia",
  "bridal packages salon",
  "top rated salons",
  "unisex salon in Banani",
  "eyebrow threading near me",
  "AC repair near me",
  "fridge repair near me",
  "TV repair services",
  "washing machine repair near me",
  "microwave repair near me",
  "laptop repair near me",
  "mobile repair shop near me",
  "electrician near me",
  "plumber near me",
  "geyser repair services",
  "fan repair near me",
  "home appliance repair",
  "generator repair near me",
  "AC gas refill service",
  "home maintenance service",
  "computer repair near me",
  "UPS repair near me",
  "inverter repair service",
  "phone screen replacement",
  "repair technician near me",
  "home cleaning near me",
  "deep cleaning services",
  "sofa cleaning service",
  "carpet cleaning near me",
  "kitchen cleaning services",
  "bathroom cleaning near me",
  "office cleaning services",
  "maid service near me",
  "pest control service",
  "disinfection services",
  "home sanitization service",
  "laundry service near me",
  "ironing services near me",
  "couch cleaning service",
  "curtain cleaning service",
  "cleaning company in Australia",
  "affordable cleaning services",
  "marble polishing service",
  "floor cleaning near me",
  "domestic help services",
  "photographer near me",
  "wedding photography",
  "event planner near me",
  "graphic designer near me",
  "logo designer services",
  "digital marketing agency",
  "SEO expert near me",
  "web developer services",
  "app developer near me",
  "IT support services",
  "freelancer in Australia",
  "tutor near me",
  "language classes near me",
  "music teacher near me",
  "home tuition in Australia",
  "accountant near me",
  "tax consultant in Australia",
  "legal advisor near me",
  "property agent near me",
  "interior designer near me",
  "car repair near me",
  "bike repair near me",
  "mechanic near me",
  "auto workshop near me",
  "car wash near me",
  "bike servicing center",
  "driver for hire",
  "vehicle towing service",
  "truck rental near me",
  "car AC repair near me",
  "battery replacement service",
  "car detailing near me",
  "rental cars in Australia",
  "bike rental near me",
  "chauffeur services",
  "pickup and drop services",
  "vehicle inspection service",
  "car modification near me",
  "tyre repair shop near me",
  "wheel alignment service",
  "wedding planner near me",
  "event decorator near me",
  "catering service near me",
  "DJ for events",
  "stage decoration services",
  "birthday party planner",
  "florist near me",
  "event photographer near me",
  "sound system rental",
  "light decoration near me",
  "party supplies near me",
  "wedding hall booking",
  "marriage registration help",
  "banquet hall in Australia",
  "affordable catering services",
  "balloon decoration near me",
  "cake delivery service",
  "event management company",
  "salon in Australia",
  "AC repair in Australia",
  "plumber in Australia",
  "best hospital in Australia",
  "car repair in Australia",
  "doctor appointment in Australia",
  "nearheal services in Australia",
  "top salons in Australia",
  "cleaning services in Australia",
  "electrician in Australia",
  "laundry service in Australia",
  "home tuition in Bogura",
  "wedding photography in Australia",
  "plumber in Gazipur",
  "digital marketing in Australia",
  "best electricians in Australia",
  "local businesses in Australia",
  "affordable salons in Australia",
  "tech support in Australia",
  "service providers in australia",
  "find services in Australia",
  "online booking in Australia",
  "register business in australia",
  "nearheal platform signup",
  "small business growth australia",
  "local services platform australia",
  "best providers in Australia",
  "hire service provider in Australia",
];

export const localStorageKey = {
  token: "accessToken",
  userInfo: "userInfo",
};
